apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
  name: {{ include "harness-delegate-ng.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "harness-delegate-ng.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3460"
        prometheus.io/path: "/api/metrics"
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap: {{ include (print .Template.BasePath "/configMap.yaml") . | sha256sum | trunc 63 }}
      labels:
        {{- include "harness-delegate-ng.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "harness-delegate-ng.serviceAccountName" . }}
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: delegate
          image: {{ .Values.delegateDockerImage }}
          {{- if .Values.securityContext.runAsRoot }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              memory: {{ include "harness-delegate-ng.assignedMemory" .}}
            requests:
              cpu: {{ .Values.cpu }}
              memory: {{ include "harness-delegate-ng.assignedMemory" .}}
          startupProbe:
            httpGet:
              path: /api/health
              port: 3460
              scheme: HTTP
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds:  {{ .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3460
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          envFrom:
            - configMapRef:
                name: {{ template "harness-delegate-ng.fullname" . }}
            - secretRef:
                name: {{ template "harness-delegate-ng.fullname" . }}
            - configMapRef:
                name: {{ template "harness-delegate-ng.fullname" . }}-proxy
                optional: true
            - secretRef:
                name: {{ template "harness-delegate-ng.fullname" . }}-proxy
                optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
