{{- if .Values.proxyUser }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
type: Opaque
data:
  # Enter base64 encoded username and password if using proxy
  PROXY_USER: {{ .Values.proxyUser }}
  PROXY_PASSWORD: {{ .Values.proxyPassword }}
{{- end }}