{{- if and (.Values.ccm.visibility) (ne .Values.k8sPermissionsType "CLUSTER_ADMIN")}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-ccm-visibility
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - nodes/proxy
      - events
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-ccm-visibility-roleBinding
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "harness-delegate-ng.fullname" . }}-ccm-visibility
subjects:
  - kind: ServiceAccount
    name: {{ include "harness-delegate-ng.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
