{{- if .Values.upgrader.enabled -}}
{{- if not .Values.upgrader.existingUpgraderToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-upgrader-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
type: Opaque
data:
  UPGRADER_TOKEN: {{ .Values.delegateToken | b64enc | quote }}
{{- end }}
{{- end }}
