{{- if .Values.upgrader.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-{{ .Values.upgrader.cronJobServiceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
{{- end }}