{{- if not .Values.existingDelegateToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
type: Opaque
data:
  # Base 64 encoded account secret
  DELEGATE_TOKEN: {{ .Values.delegateToken | b64enc | quote }}
{{- end }}
