{{- if .Values.shared_certificates.ca_bundle -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-addcerts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
type: Opaque
data:
  ca.bundle: {{ .Values.shared_certificates.ca_bundle | b64enc | quote }}
{{- end }}
