{{- if eq (include "harness-delegate-ng.useCustomRole" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-custom-roleBinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "harness-delegate-ng.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.k8sPermissionsType}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
